name: Hello World

# Events
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Workflow / Jobs
jobs:
  hello:
    runs-on: ubuntu
    steps:
      - uses: actions/checkout@v4
      - name: Hello World
      run: echo "Hello World"
      shell: bash
